language: java

jdk:
  - oraclejdk8


install: true


script:
    #- mvn compile &&
    #- command2 &&
    #- curl "http://${username}:${password}@jonas.sadjoydata.com/manager/text/undeploy?path=/" &&
